services:
  db:
    container_name: teastream-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teastream-backend

  redis:
    container_name: teastream-redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - teastream-backend

volumes:
  postgres_data:
  redis_data:

networks:
  teastream-backend:
